# CI File for the OrderManager microservice project
stages:
  - build
  - test
 
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

# This template uses jdk11 for verifying and deploying images
image: maven:3.8-jdk-11
 
cache:
  paths:
    - .m2/repository
 
build-maven:
  stage: build
  script: 
    - mvn $MAVEN_CLI_OPTS compile
 
verify: 
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    paths:
      - target/traceconsumer2-0.0.1-SNAPSHOT.jar
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
 
 
